// <auto-generated />
using System;
using App.Infra.Db.SqlServer.Ef.DbContextAgg;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infra.Db.SqlServer.Ef.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201152439_order")]
    partial class order
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Core.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.CartProduct", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "کالای دیجیتال"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "پوشاک و مد"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "لوازم خانگی"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "کتاب و لوازم تحریر"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "ورزش و سفر"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "گوشی موبایل اپل مدل iPhone 13 پرچمداری است که با تغییرات ظریف اما کلیدی نسبت به نسل قبل، تجربه‌ای بی‌نظیر را برای کاربران رقم می‌زند. این گوشی با ظرفیت 128 گیگابایت، نه تنها فضای کافی برای ذخیره هزاران عکس و ویدیو را فراهم می‌کند، بلکه با بهره‌گیری از تراشه قدرتمند A15 Bionic، سرعتی باورنکردنی در اجرای سنگین‌ترین بازی‌ها و اپلیکیشن‌های ویرایش ویدیو دارد. طراحی بدنه همچنان از لبه‌های تخت و شیشه‌ی مقاوم Ceramic Shield در جلو بهره می‌برد که مقاومت آن در برابر ضربه را چندین برابر کرده است.\r\n\r\nیکی از مهم‌ترین نقاط قوت آیفون 13، ارتقای چشمگیر دوربین‌های آن است. سنسورهای بزرگتر در دوربین عریض و فوق عریض باعث شده‌اند که جذب نور تا 47 درصد افزایش یابد؛ این یعنی عکس‌برداری در شب و محیط‌های کم‌نور با جزئیاتی خیره‌کننده همراه خواهد بود. قابلیت جدید و انقلابی Cinematic Mode نیز به شما اجازه می‌دهد ویدیوهایی با فوکوس هوشمند و عمق میدان سینمایی ضبط کنید، گویی که یک کارگردان حرفه‌ای پشت دوربین ایستاده است.\r\n\r\nصفحه‌نمایش Super Retina XDR این مدل اکنون 28 درصد روشنایی بیشتری دارد که کار با گوشی در زیر نور مستقیم خورشید را بسیار راحت‌تر کرده است. همچنین، اپل در این نسل توانسته است با بهینه‌سازی مصرف انرژی و افزایش ظرفیت فیزیکی باتری، عمر باتری را نسبت به آیفون 12 تا 2.5 ساعت افزایش دهد که برای کاربران پرمصرف خبری بسیار خوشحال‌کننده است. پشتیبانی از شبکه 5G، استاندارد ضدآب IP68 و تنوع رنگی جذاب، آیفون 13 را به یکی از کامل‌ترین گوشی‌های هوشمند بازار تبدیل کرده است که ترکیبی از زیبایی، قدرت و کارایی را ارائه می‌دهد.",
                            Image = "iphone13.jpg",
                            Inventory = 5,
                            IsDeleted = false,
                            Price = 45000000m,
                            Title = "گوشی موبایل آیفون 13"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لپ‌تاپ‌های سری TUF شرکت ایسوس همیشه نمادی از ترکیب قدرت سخت‌افزاری بالا و مقاومت فیزیکی بی‌نظیر بوده‌اند و مدل TUF Gaming F15 نیز از این قاعده مستثنی نیست. این دستگاه که برای گیمرها و طراحان گرافیک طراحی شده، بدنه‌ای با استاندارد نظامی دارد که در برابر ضربه، لرزش و تغییرات دما مقاوم است. ظاهر دستگاه با خطوط شکسته‌ و نورپردازی کیبورد RGB، حس یک ابزار جنگی مدرن را به کاربر القا می‌کند.\r\n\r\nدر دل این لپ‌تاپ، پردازنده قدرتمند نسل جدید اینتل به همراه کارت گرافیک سری NVIDIA GeForce RTX قرار گرفته است که اجرای روان جدیدترین بازی‌های روز دنیا با تنظیمات گرافیکی بالا را تضمین می‌کند. سیستم خنک‌کننده پیشرفته با لوله‌های حرارتی مسی و فن‌های چندگانه تضمین می‌کند که حتی در طولانی‌ترین جلسات بازی یا رندرهای سنگین، دمای قطعات در حد ایده‎‌آل باقی بماند و خبری از افت فریم نباشد.\r\n\r\nصفحه‌نمایش 15.6 اینچی این محصول با نرخ بروزرسانی بالا (Refresh Rate 144Hz)، تصاویری نرم و بدون پرش را نمایش می‌دهد که در بازی‌های شوتر و سرعتی، برتری قابل توجهی به گیمر می‌دهد. علاوه بر گیمینگ، این لپ‌تاپ به لطف رم بالا و حافظه SSD پرسرعت، گزینه‌ای عالی برای برنامه‌نویسان و تدوینگران ویدیو محسوب می‌شود. پورت‌های کامل شامل USB Type-C، HDMI و پورت شبکه، نیاز شما به دانگل‌های اضافی را از بین می‌برد و باتری قدرتمند آن نیز برای کارهای روزمره شارژدهی قابل قبولی دارد.",
                            Image = "asus_laptop.jpg",
                            Inventory = 0,
                            IsDeleted = false,
                            Price = 38000000m,
                            Title = "لپ تاپ ایسوس TUF Gaming"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کفش مخصوص دویدن نایکی مدل Revolution 6، تعریف جدیدی از راحتی و انعطاف‌پذیری را برای دوندگان و ورزشکاران ارائه می‌دهد. این مدل که ادامه‌دهنده راه موفق نسل‌های قبلی سری رولوشن است، با رویکردی مینیمالیستی اما کاربردی طراحی شده است. رویه‌ی کفش از پارچه‌ی مش (Mesh) تنفس‌پذیر ساخته شده که گردش هوای عالی را درون کفش ایجاد می‌کند؛ این ویژگی باعث می‌شود حتی پس از ساعت‌ها دویدن یا پیاده‌روی، پای شما خشک و خنک باقی بماند و از بوی بد جلوگیری شود.\r\n\r\nمهم‌ترین ویژگی Revolution 6، استفاده از فوم بسیار نرم در لایه‌ی میانی است که ضربات وارده از سطح زمین را به خوبی جذب می‌کند. طراحی کامپیوتری زیره بیرونی باعث شده تا هنگام برخورد پا با زمین، حالتی فنری ایجاد شود و فشار کمتری به زانوها و کمر وارد گردد. این زیره همچنین دارای الگوی خاصی است که چسبندگی بسیار بالایی روی سطوح مختلف (آسفالت، تردمیل و زمین خاکی) ایجاد می‌کند و خطر لیز خوردن را به حداقل می‌رساند.\r\n\r\nعلاوه بر کارایی فنی، نایکی در تولید این مدل به محیط زیست نیز توجه داشته و بخشی از مواد اولیه آن از پلاستیک‌های بازیافتی تهیه شده است. طراحی پاشنه تقویت‌شده باعث می‌شود پا در هنگام حرکت ثابت بماند و از پیچ‌خوردگی جلوگیری شود. این کفش با ظاهر اسپرت و مدرن خود، نه تنها برای ورزش، بلکه برای استفاده روزمره و ست کردن با لباس‌های کژوال (مانند شلوار جین یا اسلش) نیز گزینه‌ای بسیار شیک و جذاب است.",
                            Image = "nike_shoes.jpg",
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 2500000m,
                            Title = "کفش ورزشی نایکی Revolution 6"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "یخچال و فریزر دوقلو 40 فوت پارس، یکی از محبوب‌ترین و باکیفیت‌ترین محصولات برودتی ساخت ایران است که با در نظر گرفتن نیازهای خانواده‌های پرجمعیت ایرانی طراحی شده است. این محصول شامل دو دستگاه جداگانه (یک یخچال کامل و یک فریزر کامل) است که می‌توانند به هم چسبیده و یا به صورت جداگانه در آشپزخانه قرار گیرند. این ویژگی انعطاف‌پذیری بالایی را برای چیدمان در آشپزخانه‌های با ابعاد مختلف فراهم می‌کند.\r\n\r\nسیستم گردش هوای فراگیر در این مدل باعث می‌شود که سرما به صورت یکنواخت در تمام طبقات پخش شود؛ بنابراین مواد غذایی در طبقات بالا و پایین تازگی خود را به یک اندازه حفظ می‌کنند. قابلیت نوفراست (No-Frost) یا همان بدون برفک در هر دو کابین یخچال و فریزر وجود دارد، بنابراین دیگر نیازی به خاموش کردن دستگاه و دردسرهای آب کردن برفک‌ها نخواهید داشت. نمایشگر دیجیتال روی درب به شما امکان می‌دهد دمای دقیق هر بخش را مشاهده و تنظیم کنید و در صورت باز ماندن درب، سیستم اخطار صوتی شما را مطلع می‌کند.\r\n\r\nطبقات شیشه‌ای نشکن، کشوهای مخصوص میوه و سبزیجات با قابلیت حفظ رطوبت و کشوهای جادار در بخش فریزر، نظم‌دهی به مواد غذایی را بسیار آسان کرده است. موتور کم‌مصرف و عایق‌بندی استاندارد بدنه باعث شده تا این محصول رتبه انرژی مناسبی داشته باشد و هزینه‌های برق خانوار را کاهش دهد. اگر به دنبال محصولی جادار، با دوام و با خدمات پس از فروش گسترده در سراسر کشور هستید، دوقلوی پارس انتخابی هوشمندانه است.",
                            Image = "fridge.jpg",
                            Inventory = 2,
                            IsDeleted = false,
                            Price = 22000000m,
                            Title = "یخچال فریزر دوقلو پارس"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کتاب Clean Code (کدنویسی تمیز) اثر رابرت سی. مارتین که در دنیای برنامه‌نویسی با نام «عمو باب» شناخته می‌شود، بیش از آنکه یک کتاب آموزشی باشد، یک مانیفست و راهنمای اخلاقی برای توسعه‌دهندگان نرم‌افزار است. این کتاب با این پیش‌فرض شروع می‌شود که «کد نوشته می‌شود تا توسط انسان‌ها خوانده شود، نه فقط برای اجرا توسط ماشین». اگر شما کدی می‌نویسید که کار می‌کند اما خواندن و درک آن برای هم‌تیمی‌هایتان (یا حتی خودتان پس از ۶ ماه) دشوار است، این کتاب دقیقاً برای شماست.\r\n\r\nرابرت مارتین در این اثر جاودانه، اصول SOLID، نام‌گذاری صحیح متغیرها و توابع، ساختار کلاس‌ها و نحوه نوشتن کامنت‌های مفید (و پرهیز از کامنت‌های بد) را با مثال‌های عملی فراوان توضیح می‌دهد. او به شما می‌آموزد که چگونه کدهای «بد بو» (Code Smells) را شناسایی کرده و آن‌ها را بازنویسی (Refactor) کنید. فصل‌های مربوط به مدیریت خطا (Error Handling) و تست‌نویسی (Unit Testing) دیدگاه شما را نسبت به کیفیت نرم‌افزار کاملاً تغییر خواهد داد.\r\n\r\nخواندن این کتاب برای هر برنامه‌نویسی در هر سطحی (از جونیور تا ارشد) واجب است. این کتاب به شما یاد می‌دهد که تفاوت بین یک «کدنویس» معمولی و یک «مهندس نرم‌افزار حرفه‌ای» در جزئیات و تمیزی کار نهفته است. ترجمه روان و مثال‌های جاوا (که به راحتی قابل تعمیم به C# و سایر زبان‌های شی‌گرا است) باعث شده تا این کتاب به عنوان مرجع اصلی در بسیاری از شرکت‌های نرم‌افزاری بزرگ دنیا تدریس شود. با خواندن Clean Code، شما سرمایه‌گذاری بزرگی روی آینده شغلی و اعتبار حرفه‌ای خود انجام می‌دهید.",
                            Image = "clean_code_book.jpg",
                            Inventory = 100,
                            IsDeleted = false,
                            Price = 450000m,
                            Title = "کتاب Clean Code"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "سفر به دل طبیعت و کمپینگ بدون داشتن یک سرپناه امن و راحت، لطفی ندارد. چادر مسافرتی 4 نفره مدل فنری، گزینه‌ای عالی برای خانواده‌ها و گروه‌های دوستانه‌ای است که می‌خواهند آخر هفته‌ای آرام را در جنگل، کویر یا کنار دریا سپری کنند. مهم‌ترین ویژگی این چادر، مکانیزم باز و بسته شدن فنری آن است؛ به طوری که تنها در چند ثانیه برپا می‌شود و جمع کردن آن نیز بسیار ساده است، بنابراین وقت شما برای درگیری با میله‌ها و طناب‌ها تلف نمی‌شود.\r\n\r\nپارچه استفاده شده در این محصول از جنس پلی‌استر با روکش ضد آب است که شما را در برابر باران‌های ناگهانی و رطوبت زمین محافظت می‌کند. در عین حال، پنجره‌های توری‌دار بزرگ تعبیه شده در طرفین، تهویه هوای مطبوعی را ایجاد می‌کنند و با داشتن پشه‌بند، از ورود حشرات مزاحم به داخل چادر جلوگیری می‌کنند. کف چادر از پارچه‌ای ضخیم‌تر ساخته شده تا در برابر سایش سنگریزه و نفوذ رطوبت از کف مقاوم باشد.\r\n\r\nفضای داخلی این چادر برای خواب راحت 4 نفر بزرگسال طراحی شده است و ارتفاع سقف آن به گونه‌ای است که نشستن در آن راحت باشد. کیف حمل دایره‌ای شکل و وزن سبک آن باعث می‌شود تا حمل و نقل چادر در صندوق عقب خودرو یا حتی به صورت دستی بسیار آسان باشد. دوخت‌های آپارات شده و زیپ‌های باکیفیت، طول عمر این محصول را تضمین می‌کنند تا سال‌ها همسفر مطمئن شما در ماجراجویی‌هایتان باشد.",
                            Image = "camping_tent.jpg",
                            Inventory = 10,
                            IsDeleted = false,
                            Price = 1800000m,
                            Title = "چادر مسافرتی 4 نفره"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "یک کوهنورد حرفه‌ای می‌داند که کوله‌پشتی مهم‌ترین یار او در مسیرهای سخت است. کوله پشتی کوهنوردی 50 لیتری، با مهندسی ارگونومیک دقیق طراحی شده تا وزن سنگین تجهیزات را به جای شانه‌ها، روی لگن و پاها تقسیم کند. این ویژگی باعث می‌شود که حتی در پیمایش‌های طولانی و چند روزه، احساس خستگی کمتری داشته باشید و از آسیب به ستون فقرات جلوگیری شود. سیستم پشتی دارای توری عرق‌گیر است که با ایجاد فاصله بین کوله و کمر، جریان هوا را برقرار کرده و از تعریق بیش از حد جلوگیری می‌کند.\r\n\r\nظرفیت 50 لیتری این کوله فضای کافی برای کیسه خواب، لباس‌های اضافی، ظروف پخت‌وپز و آب و غذا را فراهم می‌کند. جیب‌های متعدد زیپ‌دار و کشسانی در طرفین و روی کلاهک کوله، دسترسی سریع به لوازمی مثل نقشه، قطب‌نما، بطری آب و تنقلات را ممکن می‌سازد. همچنین بندهای مخصوصی برای حمل زیرانداز، باتوم کوهنوردی و کلنگ یخ روی بدنه تعبیه شده است.\r\n\r\nجنس پارچه این کوله از نوع برزنت ضد خش و مقاوم در برابر پارگی است که در برخورد با صخره‌ها و شاخ و برگ درختان آسیب نمی‌بیند. علاوه بر این، یک کاور ضد باران (Rain Cover) در جیب مخفی پایین کوله وجود دارد که در شرایط طوفانی می‌توانید آن را روی کل کوله بکشید تا وسایلتان کاملاً خشک بمانند. سگک‌های نشکن و زیپ‌های روان YKK از دیگر ویژگی‌هایی هستند که کیفیت ساخت بالای این محصول را تضمین می‌کنند.",
                            Image = "backpack.jpg",
                            Inventory = 8,
                            IsDeleted = false,
                            Price = 3500000m,
                            Title = "کوله پشتی کوهنوردی 50 لیتری"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 10000000m,
                            IsDeleted = false,
                            Password = "123",
                            Username = "ali"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 500000m,
                            IsDeleted = false,
                            Password = "123",
                            Username = "ali_rezaei"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 0m,
                            IsDeleted = false,
                            Password = "123",
                            Username = "sara_kamali"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 2500000m,
                            IsDeleted = false,
                            Password = "123",
                            Username = "test_user"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Cart", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.CartProduct", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.Cart", "Cart")
                        .WithMany("CartProducts")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entities.Product", "Product")
                        .WithMany("CartProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Product", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Cart", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Product", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.User", b =>
                {
                    b.Navigation("Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
